// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:event_rsvp/screens/authentication/model/user/userModel.dart';
import 'package:event_rsvp/screens/event/model/attendance/attendanceModel.dart';
import 'package:event_rsvp/screens/event/model/event/eventModel.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AttendanceModelAdapter());
    registerAdapter(EventModelAdapter());
    registerAdapter(UserModelAdapter());
  }
}
